apiVersion: v1
kind: Service
metadata:
  name: example-microservice
spec:
  selector:
    app: example-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP