apiVersion: kind.x-k8s.io/v1alpha4
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRDE2bVNNQU9WTFl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1qQXlNVFEyTXpWYUZ3MHpOVEEwTVRneU1UVXhNelZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPOGJnSzM4c2prYmxXYjJ5M0UyeFpCc1MwZG1xR0ZWdlBrOUVySWtmTWEzTWNKV05XTXpsQUdYYXMKYk5oVzUvSnNUTmdZSjdLMkgvSEcvUStkdTAxbERGd1lJOEM4SGw2UmwzaGZsTjJuT2VRT2lGVzJjWnhKSmcrNQpKMGtkcmZIWVVndW8wbTlvem90RE95T1lLdE9uZEFrZ0RLdW50czVwZUJlZWgvVkNOUzkrOEdNQytySFlJeS9yCk5FQVpjREZkbDUzUlpiVFNvQnY1dEx0UkpteGdXNktJSEdMcnQzdCtycGc2dTVydUxWS3IwVDdWREVxK2o2RTgKS3Y4YXpJQ2tJdkhBdUZ0UXpiR242UWxTUW4wN2NiRmNNSDRGSDd0NFpUR2kzSTMySFA3SllPRFlLTlBMV1JOYQpCWC80M0ZWeVF4dWFaRW1aZTJjWHhiYjFQZ0FUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJReng4SWs0R2FsR3pBZkRoMzRpVE5RT3dVWkNqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXpxeVorQzB5bApFWnJZbVRCWWgwWjlOdVN1S1BZWFppWlpvZmZ4TTROaGxVWGRYa21JY3pteDlZWjhCZFU2L3JxUEhrSkVjNXN4CmJxVjdmdXNlYWlNa09nYTBpemYvL240N0grbGpFdUJ4K3N4bEJPcW9tMzNMRisvTE54SFRNYmtqazlnQ2tyVUwKbkI2M3lPWXgwaDNDb2crYUYwa05rS2hKNFpjZXhjZ1c1WHlRc3lqOFFUcVZmSlMzZGhQOEp5eVhNUE1JVlNHdQpiSUhxeVJWZ3dBajlnYUVQeU5VWCsvZjRHbUhjU09abWljQWlWS3NxTGhIRXE2cGhiYTF0SzAyV2NHRm1ZYkVyCkFRUzJIbXRrQVc0R3FLTTBBVE50M2JUNzk4Q3BWQW9TUUZWNGx2clRvenJsdld4RmpKY1BLUDM3ZG9TbTF5TGkKSjdYemd1a3lWa21RCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:32951
  name: kind-test2
contexts:
- context:
    cluster: kind-test2
    user: kind-test2
  name: kind-test2
current-context: kind-test2
kind: Cluster
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiVersion: kubeadm.k8s.io/v1beta2
  networking:
    podSubnet: "192.168.0.0/16"
  apiServer:
    extraArgs:
      authorization-mode: "AlwaysAllow"
  controllerManager:
    extraArgs:
      enable-cloud-controller: "false"
  scheduler:
    extraArgs:
      address: "0.0.0.0"
      port: "10251"
name: gitops-demo
networking:
  apiServerAddress: 127.0.0.1:6443
  apiServerPort: 6443
  disableDefaultCNI: false
  ingress:
    config:
      ssl-cert: /etc/ssl/certs/ssl-cert-snakeoil.pem
      ssl-key: /etc/ssl/private/ssl-cert-snakeoil.key
      use-http2: "true"
      use-ssl: "true"
    provider: nginx
  kubeProxyMode: iptables
nodes:
- extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  role: control-plane
- role: worker
- role: worker
users:
- name: kind-test2
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJUmpjVDVoa25QVzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1qQXlNVFEyTXpWYUZ3MHlOakEwTWpBeU1UVXhNelZhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUE5xRFYKTjFoc0Q2Z2Zac3hXQW9kNmxQaXVJOWw5OER4RDlCajQ5QVQwRWRoaDJzNTFDOHlVdXlPdE5EYno5ZXJodVcxLworSVpWcHNhKzFycEFPWjZoZ01acTJVaTF2aUdVS2FjdXpkVzY0VnRlK2ZUNXMzWFlheXo0MUVMYkFBTlIrR3RCCmJnYWI0M2t4YnIvblRJRDkzdTQ2UmpxdGwwcHpFd3BJSkhmMFRqcDZ2VmJvSVZFWGtTWlpzUlNNUTg5Qzg3UlgKWUZsQ0JLWkZzNHpFc0FWeVQyODY5SWpZS29SREozazkwK3h1SnNPRDJDaFpJMlYwd1B3dlkxaGJ1cjg3Q09zbQp2WkhJQmM2VEZ1Zm5xTTA4NmNsOFpwZDR0T3dRNTBOZHhKUjhVN2k5OGxhMDVINXh0NVh3aFRwTDdPc0NKVjBWCjJuWkJBYStQaXZ6bDgyOHhBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkRQSHdpVGdacVViTUI4TwpIZmlKTTFBN0JSa0tNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFRdUFLMU5uaUVXbGFYMlU2WWJldUNTY3NsCk96V1hkQ1d4Y3hVbFdkbUR3OGVySitsWDEzbmlrbURLUThkMTJLK0pYTUhhMVpiaWFrbkk4UVM3NW0xWkJXZDUKSmx0bGhoaDZLZGRlaHhwYVpVNDNIMDhXWnllQ0MwcjAzWGcwNFJOcDJNZ3NhaEhhYmxvUmdRd3lDZWh2RENlMwpuOEV2cXJPSGQ0eTdsS05JMi90eWlPU1ozU2s2QWcyYWNVMVg0Zjh0UEJMNEcvL3pnZzJsZTlwWVZaM0VGRTJXClp4bFZSYUd1N21xVnRjSmxadDlRUmY0SlV2Qkl3WUZkWlE0Zi92SVFYdnhlOGp1cU90ZGVPTkxzWXFrQ1BOYjYKN1NrZ3Q2U2ppSndJb0xVOXo2bW8yclFvYlZlelVuUlRZQWxwSitWM2RRUzJTWXlmR3doczJTeWQ5UmJQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBenphZzFUZFliQStvSDJiTVZnS0hlcFQ0cmlQWmZmQThRL1FZK1BRRTlCSFlZZHJPCmRRdk1sTHNqclRRMjgvWHE0Ymx0Zi9pR1ZhYkd2dGE2UURtZW9ZREdhdGxJdGI0aGxDbW5MczNWdXVGYlh2bjAKK2JOMTJHc3MrTlJDMndBRFVmaHJRVzRHbStONU1XNi81MHlBL2Q3dU9rWTZyWmRLY3hNS1NDUjM5RTQ2ZXIxVwo2Q0ZSRjVFbVdiRVVqRVBQUXZPMFYyQlpRZ1NtUmJPTXhMQUZjazl2T3ZTSTJDcUVReWQ1UGRQc2JpYkRnOWdvCldTTmxkTUQ4TDJOWVc3cS9Pd2pySnIyUnlBWE9reGJuNTZqTlBPbkpmR2FYZUxUc0VPZERYY1NVZkZPNHZmSlcKdE9SK2NiZVY4SVU2Uyt6ckFpVmRGZHAyUVFHdmo0cjg1Zk52TVFJREFRQUJBb0lCQVFDRU9idlAwdzFkaDNBaworWmdTbW5LUlNsYVY2TkowaHNRdUtLbDIwMkFGencxaEJCc1NuWURpdDdoQVlqMWUxK0lXUUJrYnZCOGNzTnZLCkU0T3VVQlpsd0tMY3MrS3Q5ckcrdGdXMDNDd3lvSE9KMjc3elNBMC9HTVVOMDRVRjhyQXJzblhldnJNQTd0cjcKTEV6UThBU3YrMzNST2RkZnhsYi9yM3EwSm5GVk54NzIxNHUvNmFhZnJMbUVOVWwyNEpGMUNhRmwxY3pxWnRRagp4dWpjeXZkRUZrcFB6ZXl3NXd3bW5RWnFZcU1FNXJqL3l6Sk53MFE4SzBGTFE3c1hJbkNUYUtPakFybUppaEd1Clp4TmFjVjkyUzNsMkpOYklZdFJsUGI2bWFtVks0ajRXT0h4QlNUem4zVWE3WEhNSFM4dHkxREdZSGVEK2xLNVYKaWN2SnZpZ0JBb0dCQU5JNC9sTmR0L0lLZ1ZYcVVGd0JyZkxHdzVHR2Y3cnhrRVVTLzNVSXJJa1dkSXZtVDQ0SQp2Z0s5dXdUaHJOOXlwR2crRlNVWXppWm1nclZsc0dtK25yVjlESUFDZTFpZ3FiSEV2TjZGNjFucTJubmxrNXFlCndzWUkxUmt6dU01bUtNbE9HNWQrSWFGZXZTdTRBSm8yajhheEo0N3E1YTZuRTZEdDZuOHFjaWhSQW9HQkFQeFYKNGZhODVKZmY2ZTFmSnFlU1ZjRlNCMmFyYXoyZVJiZnZoUi8ycUl0NDcwdG9SOXRhWWdVQUVQZ01lQkRnNkNoQQp3L1J1ZEczYUJKcHcxVmhHKzdmc1oyRDFLR2xwOEhveFB0Nzh4NzlUcUd3MENMUStRVFZ1eHJNcGJXemdiSTB5ClZzc0JXU3RHZTY4K0d4bmFkVDVndHF2V01ISHNIbWxEdVFTVVBnRGhBb0dCQUxZMXVCckNESUc2SVVnNmc5UjcKa0MzeG9la3N6dUZXSjFuM2tYdjdQTERGeWRiSWxRUGpCKzZRVE4xNlRjQ1BPWGt3OWxybEdTbW5pSHQ1M0dLTApXanlzV24xSnFXZTBPZUZmU09VRzVtdFZhSEJuVUh5Z1J1b25GYTEyYXlSYTM5Yzc0Q1o2cU9PWm5oV2Fzc3IzCnA3N3NKZ0YyRUFaRndubW1QYTVqTi9kQkFvR0JBTXFZL2Z0SVFGVjhiMnFwcWZTRE5wMG9Dazh4dE1IZGNPYTAKeGZNYTdNcEd5QUtJY0tFNjJWWmdiajlxYTRCSnc3eUYrNDhtbkE2VExIei91UnZPcWs1SzNkbm9ISkUrZ05qcQo3eXJFVkhCV2IvU29kcENaSjJ3S1REa1BPdzlleFdrOGtKa2Z0UU5jN1BPUDd0eDhIUVIvVEV0OWhwb0JWWTE0CjFYVkt2Tm1oQW9HQWJVWFZ3VnpRZzhaZ3R2dlNCVEcvMXc0SWdLbEdWRnU1bU1WT2dUVFFaWUNTTytQMVc5ZDEKOHZzVGhUREQ2TDhXcE4yZDR1RGVpOEVVUjJLTWdtbXMwUkUwMTU1V0R0TDN4NkxqajBZOWtrWHJ6amNFSm81ZgpDcWcvaVZCRmRSWnBUUjl4bGZOd1VKNjZGdFFKbk9SWFBkb2h2MzNzYkJnalFBcDM5MFZQK2lBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
